#!/usr/bin/env node
/*jshint node:true*/
/* vim: set ft=javascript: */
"use strict";

var path = require('path');

if (process.argv.length < 3) {
  var commandName = process.argv[1].split('/').slice(-1)[0];
  console.log("Usage:");
  console.log(' ' + commandName + ' data');
  console.log('  data being a directory path, and data.json the settings file.');
  console.log('  See https://github.com/madec-project/ezvis for more details.');
  process.exit(1);

}

require('castor-core')(require('./server.js'));
